git_repository(
    name = "org_dropbox_rules_node",
    remote = "https://github.com/dropbox/rules_node.git",
    commit = "4fe6494f3f8d1a272d47d32ecc66698f6c43ed09",
)

load("@org_dropbox_rules_node//node:defs.bzl", "node_repositories")

node_repositories()
