git_repository(
    name = "nodejs",
    remote = "https://github.com/bazelbuild/rules_nodejs.git",
    tag = "0.9.1", # check for the latest tag when you install
)

git_repository(
    name = "io_bazel_skydoc",
    remote = "https://github.com/bazelbuild/skydoc.git",
    tag = "0.1.4", # check for the latest tag when you install
)

load("@nodejs//:defs.bzl", "node_repositories")
load("@nodejs//:defs.bzl", "npm_install")

node_repositories(
    package_json = ["//:package.json"],
    node_path = "/usr/local/bin/node",
    #node_version = "10.2.1"
)

npm_install(
    name = "ping",
    package_json = "//module_b:package.json",
)
